---
- block:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy nginx config (optional)
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload nginx
      when: nginx_conf is defined

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
  tags: nginx
